### ISSUE TITLE
Broken in Python v3.10

### ISSUE THREAD

**Issue by hexiro** [perkfly/aioify#23]
I found this issue in `aioify`'s dependency, `module-wrapper`'s repository:
https://github.com/rominf/module-wrapper/issues/2

"""
It seems like importing the package in Python 3.10.1 will raise
```
FileNotFoundError: [Errno 2] No such file or directory: '/.../python3.10/site-packages/stdlib_list/lists/3.10.txt'
```
"""

Would it be possible to remove this dependency to fix the issue of not having py3.10 support?

**Comment by rominf** [comment]
Hi. Sorry for the very long delay. I've put the library into maintenance mode (see reasons and proper ways to do similar things in README.md). Most of the work happens in `module_wrapper`, which relies on `stdlib_list`, which doesn't support Python 3.10, and fixing the library is not a trivial task, especially without proper testing.

**Comment by hexiro** [comment]
fair enough 👍🏼
